trigger: none # Only run this pipeline when manually triggered

resources:
  pipelines:
    - pipeline: vscode-azurevirtualmachines # identifier to use in pipeline resource variables
      source: \Azure Tools\VSCode\Extensions\vscode-azurevirtualmachines # name of the pipeline that produces the artifacts

steps:
  - script: |
      echo $(resources.pipeline.vscode-azurevirtualmachines.pipelineID)
      echo $(resources.pipeline.vscode-azurevirtualmachines.runName)
      echo $(resources.pipeline.vscode-azurevirtualmachines.runID)
      echo $(resources.pipeline.vscode-azurevirtualmachines.runURI)
      echo $(resources.pipeline.vscode-azurevirtualmachines.sourceBranch)
      echo $(resources.pipeline.vscode-azurevirtualmachines.sourceCommit)
      echo $(resources.pipeline.vscode-azurevirtualmachines.sourceProvider)
      echo $(resources.pipeline.vscode-azurevirtualmachines.requestedFor)
      echo $(resources.pipeline.vscode-azurevirtualmachines.requestedForID)

  - task: DownloadPipelineArtifact@2
    displayName: Download VSIX
    inputs:
      source: specific # download from a different run
      project: DevDiv
      definition: $(resources.pipeline.vscode-azurevirtualmachines.pipelineID)
      buildVersionToDownload: specific
      runId: $(resources.pipeline.vscode-azurevirtualmachines.runID)
