trigger: none # Only run this pipeline when manually triggered

resources:
  pipelines:
    - pipeline: vscode-azurevirtualmachines # identifier to use in pipeline resource variables
      source: \Azure Tools\VSCode\Extensions\vscode-azurevirtualmachines # name of the pipeline that produces the artifacts

steps:
  - checkout: none
  - script: |
      echo $(resources.pipeline.vscode-azurevirtualmachines.pipelineID)
      echo $(resources.pipeline.vscode-azurevirtualmachines.runName)
      echo $(resources.pipeline.vscode-azurevirtualmachines.runID)
      echo $(resources.pipeline.vscode-azurevirtualmachines.runURI)
      echo $(resources.pipeline.vscode-azurevirtualmachines.sourceBranch)
      echo $(resources.pipeline.vscode-azurevirtualmachines.sourceCommit)
      echo $(resources.pipeline.vscode-azurevirtualmachines.sourceProvider)
      echo $(resources.pipeline.vscode-azurevirtualmachines.requestedFor)
      echo $(resources.pipeline.vscode-azurevirtualmachines.requestedForID)

  - task: DownloadPipelineArtifact@2
    displayName: Download VSIX
    inputs:
      source: specific # download from a different run
      project: DevDiv
      definition: $(resources.pipeline.vscode-azurevirtualmachines.pipelineID)
      buildVersionToDownload: specific
      runId: $(resources.pipeline.vscode-azurevirtualmachines.runID)
      artifact: Build Root
      targetPath: $(System.DefaultWorkingDirectory)

  - script: |
      dir

  - script: npm i -g @vscode/vsce
    displayName: "Install vsce"

  - task: AzureCLI@2
    displayName: Get userId of WIF
    inputs:
      azureSubscription: AzCodeReleases
      scriptType: pscore
      scriptLocation: inlineScript
      inlineScript: |
        az account show

  - task: AzureCLI@2
    displayName: Get userId of WIF 2
    inputs:
      azureSubscription: AzCodeReleases
      scriptType: pscore
      scriptLocation: inlineScript
      inlineScript: |
        az

  - script: |
      # Find all .vsix files in the working directory
      vsixFiles=$(find $(Build.SourcesDirectory) -maxdepth 1 -type f -name '*.vsix')

      # Count the number of .vsix files
      count=$(echo "$vsixFiles" | wc -l)

      # Check if more than one .vsix file is found. We don't want to accidentially release the wrong .vsix.
      if [ "$count" -gt 1 ]; then
        echo "More than one .vsix file found. The pipeline will fail."
        exit 1
      elif [ "$count" -eq 0 ]; then
        echo "No .vsix files found. The pipeline will fail."
        exit 1
      else
        # Set the pipeline variable
        vsixFileName=$(basename "$vsixFiles")
        echo "##vso[task.setvariable variable=vsixFileName;]$vsixFileName"
        echo "Found .vsix file: $vsixFileName"
      fi
    displayName: "Find and Set .vsix File Variable"

  - script: |
      echo $(vsixFileName)

  # - task: AzureCLI@2
  #   displayName: Run vsce publish
  #   inputs:
  #     azureSubscription: AzCodeReleases
  #     scriptType: pscore
  #     scriptLocation: inlineScript
  #     inlineScript: |
  #       $publishArgs = @(
  #         '--azure-credential'
  #         '--packagePath'
  #         '$(vsixFileName)'
  #         '--manifestPath extension.manifest'
  #         '--signaturePath extension.signature.p7s'
  #       )
  #       npm run publish -- @publishArgs
